name: Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      confirm:
        required: true
        description: "WARNING this triggers a production rollout"
  release:
    types:
      - created
    branches:
      - main
###
jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Read Version
        id: version
        run: |
          echo "Reading package.json"
          PACKAGE_VERSION=$(cat ./package.json | jq '.version' | tr -d '"')
          echo ::set-output name=value::$PACKAGE_VERSION-build.${{ github.run_id }}
      - name: Select Environment
        id: environment
        run: |
          COMMIT_MSG="$(git log -1 --pretty=%B)"
          echo $COMMIT_MSG
          if [[  "$COMMIT_MSG" == *"_ci"* ]]; then
            echo "::set-output name=value::ci"
          else
            if [[ "${{ github.ref_name }}" == "develop" ]]; then
              echo "::set-output name=branch::staging"
            elif [[ "${{ github.ref_name }}" == "main" ]]; then
              echo "::set-output name=branch::production"
            elif [[ "${{ github.ref_name }}" == "build/cicd" }} ]]; then
              echo "::set-output name=branch::staging"
            else 
              echo "No result"
            fi
          fi

      - name: Check Environment
        run: |
          if [[ "${{ steps.environment.outputs.value }}" != "ci" && "${{ steps.environment.outputs.value }}" != "staging" && "${{ steps.environment.outputs.value }}" != "production" ]]; then
            echo "Invalid Environment: ${{ steps.environment.outputs.value }}"
            exit 1
          fi
          echo "Environment: ${{ steps.environment.outputs.value }}"
    outputs:
      version: ${{ steps.version.outputs.value  }}
      environment: ${{ steps.environment.outputs.value  }}
      condition: ${{ steps.environment.outputs.condition  }}

####
  rollout:
    name: Rollout
    if: needs.prepare.outputs.condition != 'ci'
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - name: Check Stage
        if: needs.prepare.outputs.environment == 'staging'
        run: echo "staging"
      - name: Check Prod Standart
        if: needs.prepare.outputs.environment == 'production'
        run: echo "production wo cron"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Kubernetes staging context
        uses: Azure/k8s-set-context@v2
        if: needs.prepare.outputs.environment == 'staging'
        with:
          method: service-account
          k8s-url: ${{ secrets.K8S_STAGE_ENDPOINT }}
          k8s-secret: ${{ secrets.K8S_STAGE_ACCOUNT }}
      - name: Kubernetes cron context
        uses: Azure/k8s-set-context@v2
        if: needs.prepare.outputs.environment == 'production'
        with:
          method: service-account
          k8s-url: ${{ secrets.K8S_PRODUCTION_ENDPOINT }}
          k8s-secret: ${{ secrets.K8S_PRODUCTION_ACCOUNT }}
      - name: Check workflow stage
        if: needs.prepare.outputs.environment == 'staging'
        run: |
              kubectl get pods
      - name: Check workflow cron
        if: needs.prepare.outputs.environment == 'cronjob'
        run: |
              kubectl get pods -n cronjobs
      - name: Check commit
        run: |
              echo "Commit message: ${{ github.event.head_commit.message }}"
              echo "Commit tag: ${{ github.event.release.tag_name }}"
              echo "Branch: ${{ github.ref_name }}"
